### ISSUE TITLE
#Challenge 01

### ISSUE THREAD

**Issue by RustyLobster** [RustyLobster/challenge-01-manage-landing-page#1]
# To-do
## Navbar
- [ ] Responsive hamburger
  - [ ] How to place the mobile navbar div with `absolute`?

## Testimonials
- [ ] Sliding testimonials with animation. 

# Solved
- [x] Responsive `background-color` using `@media (max-width: 1024px)`
  - [x] There is a tailwind bug with customisation on `tailwind.config.js`: if I write custom variables, all the default tailwind variables are gone and they don't take effect anymore. For instance:
    - `screens: { bp-desktop }` will nullify the effects of the tailwind default breakpoints (`sm`, `md`, `lg`, `xl`, `2xl`).
    - So the workaround for this is defining custom min-width and max-width in `input.css` with `@tailwind` tags that will be converted to `output.css`.
